### ISSUE TITLE
Debugging

### ISSUE THREAD

**Issue by weepy** [q-p/SoundPusher#10]
Hiya - how can I go about debugging the audio driver ?

**Comment by q-p** [comment]
The notes from [BackgroundMusic](https://github.com/kyleneideck/BackgroundMusic/blob/master/DEVELOPING.md) on debugging should be applicable here as well, so you probably need to disable system integrity protection (SIP).

**Comment by weepy** [comment]
Hey - thanks - is that how you do it or are u on an earlier mac-os ?

**Comment by q-p** [comment]
I mainly did "classic" `printf` debugging and didn't attempt to attach a debugger...

**Comment by weepy** [comment]
Hey thanks!

I got the driver running ok.

I wanted to be able to set the main output to be "Loopback Audio" and it to
come out of the main speakers.  Do you know how I might achieve that ? Do I
need to run the app as well to do that ?

thanks

Jonah

**Comment by q-p** [comment]
Yes, `SoundPusher.app` reads from `Loopback Audio` and sends the (encoded) data to the default digital output device.

**Comment by weepy** [comment]
Cool - thanks!
I got the Pusher app and the driver running ok!
I hope you don't mind me asking - do you have any ideas about how to output
the sound from Loopback Audio to the main output ?

**Comment by weepy** [comment]
... I don't have a digital output - so the Pusher app doesn't get into most
of the App code.

Am I right in thinking that I need it to do something like  :

```

 *const* *auto* &inDevice = loopbackDevices.front();

    *const* *auto* &outDevice = *outDeviceIt;

    *const* *auto* &outStream = outDevice._streams[attempt.outStreamIndex];

    *try*

    { *// create and start-up first*

      *auto* newChain = std::make_unique<ForwardingChain>(attempt,
inDevice._device, inDevice._streams.front()._stream,

        outDevice._device, outStream._stream, outStream._formats.front(),
kAudioChannelLayoutTag_AudioUnit_5_1);


      newChain->_output.SetUpmix(_enableUpmix);


      newChain->_input.Start();

      newChain->_output.Start();


      *// and only add if everything worked so far*

      _chains.emplace_back(std::move(newChain));

    }

```


Currently outStream is the Digital devices ... maybe I want to change it to
System output ?

**Comment by q-p** [comment]
I think you'll have to change many small assumptions strewn throughout the code (and I have no personal interest in doing that).

You would probably be better off looking apps that don't make the "encoded digital output" assumption to start with, such as [Soundflower](https://github.com/mattingalls/Soundflower) or [Loopback](https://rogueamoeba.com/loopback/).

**Comment by weepy** [comment]
Yes of course I wouldn't expect you to do that !

I think your code seems fairly straightforward. I've managed to enumerate
the non digital outputs and compile it without the encoding libraries.

I'm guess that DigitalOutputContext will not be used.

Any idea if ForwardingChainIdentifier and ForwardingInputTap are only
relevant to digital output ?

J

**Comment by q-p** [comment]
You still need something that reads input (from Loopback Audio) and forwards it to the actual output device, and the `ForwardingInputTap` is (currently) does this job.

The `ForwardingChainIdentifier` is a mapping from which input device's data is sent to which output device.

**Comment by malikAr** [comment]
How to pass my socket data to loopback driver instead from microphone.
