### ISSUE TITLE
Using Loopback in a dspPlugin

### ISSUE THREAD

**Issue by fabriceo** [q-p/SoundPusher#11]
Hi Q-P thanks for sharing this is an awesome and inspiring solution!
may I use the GitHub channel here to ask some guidance for me to reuse the loopback audio driver, and then I put a small context here:

I have created a virtual audio DSPKernel framework with a concept of opcodes, an encoder and a runtime. all is working perfectly fine and I m able to create dsp solution embedded in external dac like the one from oktoresearch. Also this is running fine with also on linux with alsa loopback :) now I d like to run my opcodes and the runtime interpreter within your loopback audio driver. In other words the loopback would includes my runtime interpreter and then the outputs would be the inputs treated by the custom dsp prog.

my problem is really basic, where do I start to modify your loopback project in Xcode and can I reuse your plist as is ?

if you look in my AVDSP repo, you ll find the linux folder with the also integration and also an osx folder with a dprunosx.c which aims at testing the dsp runtime core but now I need to pass real audio trough it :)

many thanks in advance

**Comment by q-p** [comment]
You need to make sure to change all names, UUIDs, strings (localized or not), and most certainly bundle identifiers. You might be better off starting from Apple's NullAudio sample code 🤷‍♀.
