### ISSUE TITLE
License & Tutorial/helpful Links & Debugging info

### ISSUE THREAD

**Issue by Raj123456788** [q-p/SoundPusher#14]
Thank you so much for this repo. 

Loopback Audio was purchased by a company and I want to make sure this repo is MIT (Free to use and distribute) commercially.

Can you please post tutorial/links for a rookie to start/understand the SOund Pusher.

How can I debug soundpusher where it will hit the break points in Xcode? Makes life easier!

Thanks you in advance!

**Comment by Raj123456788** [comment]
Followed this link[https://github.com/kyleneideck/BackgroundMusic/blob/master/DEVELOPING.md#building-and-debugging](url) but getting systemIntergrity protection despite of giving full disk read access. Is there easy way to debug this?

**Comment by q-p** [comment]
System Integrity Protection != "Full Disk Read Access". I think you're in over your head... (And no, there is no easy way to debug `AudioServerPlugIns` anymore).

**Comment by Raj123456788** [comment]
Hey, just new to Xcode & osx itself. Have worked on windows platform for years. I saw https://appletoolbox.com/seeing-error-operation-not-permitted-in-macos-mojave/ which talked about It Starts With Apple’s System Integrity Protection and said full drive access might work. Will Keep trying. And Video Plugin debugging was pretty easy courtesy https://github.com/lvsti/Cameo by opening camera window.  Thanks for replying!
