### ISSUE TITLE
'libavutil/opt.h' file not found

### ISSUE THREAD

**Issue by Raj123456788** [q-p/SoundPusher#16]
Followed https://superuser.com/questions/624561/install-ffmpeg-on-os-x
to install the ffmpeg

Is there specific ffmpeg version or installer needed to be installed?

**Comment by q-p** [comment]
Check the build settings of the `SoundPusher` target, it refers to `$FFMPEG_HOME`. This variable can be set in Xcode Preferences => Locations => Custom Paths.

**Comment by Raj123456788** [comment]
Still giving me same error. Please tell me if I am missing anything.
![Uploading Screen Shot 2020-12-31 at 10.35.58 AM.png…]()

**Comment by Raj123456788** [comment]
above solution worked. thanks!
