### ISSUE TITLE
can't find the ffmpeg library?

### ISSUE THREAD

**Issue by liuyaxin** [q-p/SoundPusher#18]
How to solve the problem?
<img width="268" alt="截屏2021-03-04 下午2 22 12" src="https://user-images.githubusercontent.com/3119496/109920268-01905500-7cf5-11eb-8f0f-87ef7f859fc8.png">

**Comment by q-p** [comment]
Look at the build settings for `SoundPusher`. They refer to the variable `$FFMPEG_HOME`. That must be set and point to the directory where your FFmpeg is installed.

That must be set in Xcode's `Preferences` -> `Locations` -> `Custom Paths` -> Add `FFMPEG_HOME` and point it to the right location.

**Comment by q-p** [comment]
Fixed (explained) with 7fba1a4a00a3786349ff7210b038e6ea6377e916
