### ISSUE TITLE
Produce a similar project for headphone downmix?

### ISSUE THREAD

**Issue by kode54** [q-p/SoundPusher#2]
I have compiled some headphone downmix impulses at:

https://github.com/kode54/dh

With this convolver, one could downmix 5.0 (the LFE impulses are null) to stereo, in three space size presets, at various sample rates.

**Comment by q-p** [comment]
Hmmmmmm. There's already http://hajoheadphone.com that does something along these lines, I think.

Integrating something like this into `SoundPusher.app` would mean refactoring the output-side of the chain as well as some of the set-up code (e.g. enumerating and selecting the output formats). I personally don't use headphones, but I'm not averse to merging something like this if there's interest.

`SoundPusher.app` already uses FFmpeg, so if one wanted to do a headphone down mix, I'd either use af_sofalizer (but I currently don't use any FFmpeg filters) or hope that swresample gains such an ability in its down mix.

**Comment by q-p** [comment]
I don't think this makes sense to do here (i.e. in SoundPusher.app). Using FFmpeg to do a binaural downmix could happen, but I have no interest in doing that.
