### ISSUE TITLE
macOS Monterey beta sees SoundPusher as a Microphone

### ISSUE THREAD

**Issue by DaveFlashNL** [q-p/SoundPusher#20]
as said above in titel, this result in a microphone access indicator to show up in control center/menubar and overlaid on top of full playing video's in right top corner, example: https://i.postimg.cc/2yf8VySZ/IMG-0628.jpg

please investigate if there's an easy fix. application and virtual audio device otherwise work as expected under macOS 12, it's just very irritating as it ruins watching a movie or some such.

**Comment by q-p** [comment]
This is not new in macOS Monterey. What is new is the persistent, overlaid microphone indicator.

Offhand, I can't think of a way to avoid this as long as it considers reading from the virtual audio device as consuming microphone input.

I also won't be perusing the betas, so it may be some time until get around to play with it myself. If anyone has any clever ideas, let me know.

**Comment by q-p** [comment]
I did leave a bug report with Apple about this, but it came back as 

> Investigation complete - Works as currently designed

**Comment by q-p** [comment]
I can now confirm this happens. I don't like it, but I also don't know of a way around it. ☹️

**Comment by DaveFlashNL** [comment]
> I did leave a bug report with Apple about this, but it came back as
> 
> > Investigation complete - Works as currently designed

damn apple, this is frustrating, it's designed to be obnoxious?

**Comment by q-p** [comment]
Here's a work-around for hiding the dot (but I probably will not include such a hack in SoundPusher itself as it might also hide "real" microphone dots) https://github.com/s4y/undot

**Comment by DaveFlashNL** [comment]
nice! but this needs terminal to remain open?
