### ISSUE TITLE
Basic installation- Unable to see audio device

### ISSUE THREAD

**Issue by zzph** [q-p/SoundPusher#21]
Hi there,

This looks great.

However, I can't get it to work. I'm wondering if I missed a step?

1) I downloaded `SoundPusherAudio.driver.zip` and extracted the folder to `/Library/Audio/Plug-Ins/HAL`
2) I opened `SoundPusher` app

Under my Audio Devices, I don't see a new device. Also, the options in SoundPusher are greyed out.

Any ideas? I'm on Intel Mac, 11.5 (big Sur)

Cheers

**Comment by q-p** [comment]
I'm assuming you were able to solve this and there isn't an underlying issue.
