### ISSUE TITLE
Hearing popping notification sound when I'm not playing anything in background

### ISSUE THREAD

**Issue by jqqqqqqqqqq** [q-p/SoundPusher#26]
## Main issue
Hearing some weird popping sounds and twisted output on some content. This only happens when the soundbar is starting to play something.

### Get the audio file
Open any verizon website and open the "chat with us" on bottom right. The pop up sound is not the same as my internal speaker. It's kind of cracked. I believe this is a short audio with high frequency. Not sure

Example website I use: https://www.verizon.com/smartphones 
Or you can probably just download from their CDN:
https://lpcdn.lpsnmedia.net/le_unified_window/10.24.1.0-release_5557/resources/audio/kpSoundEffect.wav

### How to trigger the popping sound
1. Make sure nothing is playing in background
2. Drag/play the file in Google Chrome (Not working in apple music, it's works just fine)
3. For the first time of playing, I can hear popping sound. The second time it works fine.

If I'm playing music or other content in background, I cannot reproduce the issue.

## Potential solution
Add a feature to play some inaudible sound to prevent output device from sleeping.

## Devices I use

I'm using a Mac Studio with Soundblaster X4 and connecting to my Sonos Beam using S/PDIF.

## Logs might or might not be related
```
coreaudiod: (libAudioIssueDetector.dylib) [com.apple.coreaudio:aid] IssueReporting.cpp:495   RTAID [ use_case=Generic report_type=RMS Generic Chain clientID=HAL node=-Input issue_detected_sample_time=12543040.000000 ] -- [ -41.296379, -5.939562 ]
```

## What is working
Pretty much everything else is working. I can listen to Apple music with dolby atmos and everything works fine. Stereo upmix is also working, I can hear the difference between on and off.

**Comment by jqqqqqqqqqq** [comment]
I tried to tweak the factor between 1.0 and 16.0 but nothing works so far. I tried to restart the GUI program during the change, should I reboot my computer each time?

Any suggestions? Thanks!

**Comment by q-p** [comment]
Did you try the [new version](https://github.com/q-p/SoundPusher/releases/tag/v1.4.1) I've uploaded today? That has nothing to do with the `SafetyFactor` from the last release.

(And I've you had to adjust, you may try deleting it to go back to the default...)

**Comment by jqqqqqqqqqq** [comment]
Confirmed after a reboot, it works like a charm. Thanks a lot for the quick update!!!
