### ISSUE TITLE
Feature request: recompile SoundPusher as a VLC plugin

### ISSUE THREAD

**Issue by DaveFlashNL** [q-p/SoundPusher#28]
Just as the title says, would it be possible for you, to rework your SoundPusher as a plugin for VLC, so VLC, with this plugin, could do all the audio stuff such as upconverting to 5.1 from stereo and if the audio is say, DTS, convert to Dolby 5.1 and have vlc itself handle the resultant audio to spdif. So Instead of routing the audio from VLC to SoundPusher Virtual device to spdif.

Saving a step, and more importantly: as such to also prevent the annoying orange dot of showing up in the upper right corner of your screen, on top of everything and especially when playing fullscreen video.

**Comment by q-p** [comment]
It might be possible, but I have no interest in doing so. In either case, this would be a separate project.

**Comment by DaveFlashNL** [comment]
> It might be possible, but I have no interest in doing so. In either case, this would be a separate project.

ah ok. it's sad I lack the knowledge to do so. so maybe one day you could do it. As I don't see apple reversing course on that annoying orange dot in the upper right corner, even on top of playing content in fullscreen anytime soon. All efforts such as undot, also on gtihub, have been circumvented by apple in ways that only if you disable SIP, you could re-circumvent again and remove the dot from overlaying on top of the screen. But ofc, disabling SIP is not something for the average user and even most devs are against. SIP is an essential security system on Apple's operating systems.
