### ISSUE TITLE
OSSpinLock

### ISSUE THREAD

**Issue by trimonkee** [q-p/SoundPusher#4]
Hi,

First of all thank you for creating this project. I'm doing some experimentation based on the Loopback driver and am seeing this deprecation notice.
Development/Audio_Drivers/SoundPusher/LoopbackAudio/LoopbackAudio.c:2813:2: 'OSSpinLockUnlock' is deprecated: first deprecated in macOS 10.12 - Use os_unfair_lock_unlock() from <os/lock.h> instead.

I'm going to work on cleaning that up. Can I have you take a look after I'm done.

**Comment by q-p** [comment]
Sure.

I never saw those deprecations because I have the deployment target set to 10.10, but at some point might as well up that to 10.12 I guess. Which means the logging should probably move to `os_log` too.

**Comment by trimonkee** [comment]
Ok I'll take a look at that as well

**Comment by q-p** [comment]
Fixed in db4ff502cf03569b82f4a1c53daa57d7d691ccb7
