### ISSUE TITLE
driver issue in mojave 10.14

### ISSUE THREAD

**Issue by polywh96** [q-p/SoundPusher#7]
Tested LoopbackAudio driver in mojave 10.14, no audio from driver.What is the different in mojave?

**Comment by q-p** [comment]
Works for me. Did you allow / double check the "Security & Privacy" / Privacy / Microphone System Preferences that allow SoundPusher to access audio input (which is confusingly called "Microphone")?

**Comment by polywh96** [comment]
yes, I used LoopbackAudio as driver to get the system audio, in my test, LoopbackAudio works fine before 10.14, but after upgrade to 10.14, no audio from it.
