### ISSUE TITLE
No (digital) output device on Mojave 10.14.1

### ISSUE THREAD

**Issue by change2hao** [q-p/SoundPusher#8]
I have copy the LoopbackAudio.driver to HAL folder and open the SoundPusher.app on Mojave 10.14.1, unfortunately there is no digital output device, such as follows

<img width="206" alt="screenshot 2018-11-26 at 1 07 46 pm" src="https://user-images.githubusercontent.com/2145205/48994297-78852d80-f17d-11e8-8829-7265c3a6a911.png">

and I check the Security & Privacy option, such as follows

![image](https://user-images.githubusercontent.com/2145205/48994247-36f48280-f17d-11e8-9f90-2d2b43419266.png)

I just want to record the system sound / microphone, the app could support this?

**Comment by q-p** [comment]
If all you want is to record system audio, you should be able to ignore SoundPusher.app, and just set `Loopback Audio` as the default audio device (under System Preferences – Sound – Output) and record from that. Remember that you need to restart `coreaudiod` (or just reboot) for the driver to show up. I'm also not sure if you'll have quarantine problems if you install it manually.

But there's plenty apps that are probably better suited for that (SoundFlower, Loopback from Rogue Amoeba, ...).

**Comment by change2hao** [comment]
> If all you want is to record system audio, you should be able to ignore SoundPusher.app, and just set `Loopback Audio` as the default audio device (under System Preferences – Sound – Output) and record from that. Remember that you need to restart `coreaudiod` (or just reboot) for the driver to show up. I'm also not sure if you'll have quarantine problems if you install it manually.
> 
> But there's plenty apps that are probably better suited for that (SoundFlower, Loopback from Rogue Amoeba, ...).

so I cannot figure out what's the app's main feature and when the digital output device option is available and who is the target user of this app. I'm the layman, but I'm full of curiosity, could you give me a case to explain what's magic of the app, thank you 😊

**Comment by q-p** [comment]
Whether you have a digital output device depend on your hardware / attached audio interfaces. If you don't have it, then the app is useless to you. :)
