### ISSUE TITLE
Change volume of HDMI TVs or DisplayPort monitors with built-in speakers?

### ISSUE THREAD

**Issue by carlosfilhoadm** [q-p/SoundPusher#9]
I apologize if the question seems absurdly stupid (I'm not exactly a specialist on virtual sound devices):

Does SoundPusher allow to use macOS volume controls on screens with built-in speakers connected through HDMI/DisplayPort, like e.g. Sound Control (https://staticz.com)?

Another very inaccurate example (since it uses DDC/CI rather than virtual audio devices) of such functionality is MonitorControl (https://github.com/the0neyouseek/MonitorControl).

Thanks.

**Comment by q-p** [comment]
No, this doesn't help with (and it can't be done through TOSLINK - you'd need to look at something that deals directly with HDMI, I think).
